# Tensor Manipulation

In [1]:
# https://www.tensorflow.org/api_guides/python/array_ops
import tensorflow as tf
import numpy as np
import pprint  # pprint模块 提供了打印出任何Python数据结构类和方法
tf.set_random_seed(777)  # for reproducibility

pp = pprint.PrettyPrinter(indent=4)
sess = tf.InteractiveSession()

## Simple Array

In [2]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
pp.pprint(t)
print('t.ndim:',t.ndim) # rank
print('t.shape:',t.shape) # shape
print(t[0], t[1], t[-1])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])

array([0., 1., 2., 3., 4., 5., 6.])
t.ndim: 1
t.shape: (7,)
0.0 1.0 6.0
[2. 3. 4.] [4. 5.]
[0. 1.] [3. 4. 5. 6.]


# 2D Array

In [3]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
pp.pprint(t)
print('t.ndim:',t.ndim) # rank
print('t.shape:',t.shape) # shape

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])
t.ndim: 2
t.shape: (4, 3)


## Shape, Rank, Axis

In [4]:
t = tf.constant([1,2,3,4])
tf.shape(t).eval()

array([4])

In [5]:
t = tf.constant([[1,2],
                 [3,4]])
tf.shape(t).eval()

array([2, 2])

In [6]:
t = tf.constant([[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],[[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]])
tf.shape(t).eval()

array([1, 2, 3, 4])

In [8]:
[
    [
        [
            [1,2,3,4], 
            [5,6,7,8],
            [9,10,11,12]
        ],
        [
            [13,14,15,16],
            [17,18,19,20], 
            [21,22,23,24]
        ]
    ]
]

[[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
  [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]]

## Matmul VS multiply

tf.matmul(a, b, transpose_a=False, transpose_b=False, adjoint_a=False, adjoint_b=False, a_is_sparse=False, b_is_sparse=False, name=None)

In [13]:
# 矩阵乘法
matrix1 = tf.constant([[3., 3.]]) # shape: 1x2
matrix2 = tf.constant([[2.],[2.]]) # shape: 2x1
tf.matmul(matrix1, matrix2).eval() # shape: 1x1

array([[12.]], dtype=float32)

In [17]:
# 点乘 element-wise
(matrix1*matrix2).eval()

array([[6., 6.],
       [6., 6.]], dtype=float32)

## Watch out broadcasting
### 二维数组

In [29]:
matrix1 = tf.constant([[0, 0, 0],[1, 1, 1],[2,2,2],[3,3,3]]) #shape (4,3)
matrix2 = tf.constant([[1],[2],[3],[4]]) # shape (4,1)
(matrix1+matrix2).eval() # shape (4,3)

array([[1, 1, 1],
       [3, 3, 3],
       [5, 5, 5],
       [7, 7, 7]])

![broadcasting](./image/broadcasting.png)  
>将matrix2在轴1上复制三份变成形状（4,3）的数组，再与matrix1进行计算

### 三维数组

In [28]:
matrix1 = tf.constant(np.arange(24).reshape(3,4,2)) # shape 3x4x2
matrix2 = tf.constant(np.arange(8).reshape(4,2)) # shape 4x2
(matrix1+matrix2).eval() #shape 3x4x2

array([[[ 0,  2],
        [ 4,  6],
        [ 8, 10],
        [12, 14]],

       [[ 8, 10],
        [12, 14],
        [16, 18],
        [20, 22]],

       [[16, 18],
        [20, 22],
        [24, 26],
        [28, 30]]])

![broadcasting](./image/broadcasting3.png)  
>将matrix2 在轴0上复制三份形状变为（3,4,2）再进行计算

## Random values for variable initializations 

In [35]:
# 从正态分布中输出随机值
tf.random_normal(shape=[3],mean=0.0,stddev=1.0,dtype=tf.float32,seed=1).eval() 

array([-1.1319157 , -0.36276877,  1.3904845 ], dtype=float32)

In [39]:
# 从均匀分布中返回随机值,默认范围是[0,1)左闭右开区间
tf.random_uniform(shape=[2],minval=0,maxval=1,dtype=tf.float32,seed=1).eval()

array([0.4934088, 0.7006384], dtype=float32)

In [42]:
# 截断的正态分布函数。生成的值遵循一个正态分布，但不会大于平均值2个标准差
tf.truncated_normal(shape=[2, 3],mean=0.0,stddev=1.0,dtype=tf.float32,seed=1).eval()

array([[-1.1319157 , -0.36276877,  1.3904845 ],
       [-0.8198092 , -1.2804945 , -0.51075715]], dtype=float32)

## Reduce Mean/Sum

tf.reduce_mean(
    input_tensor,
    axis=None,
    keepdims=None,
    name=None,
    reduction_indices=None,
    keep_dims=None
)

In [44]:
tf.reduce_mean([1, 2], axis=0).eval() # 注意数据类型

1

In [47]:
x = [[1., 2.],
     [3., 4.]]
tf.reduce_mean(x).eval() # 默认对所有元素求平均值,将所有维度都减少

2.5

In [48]:
tf.reduce_mean(x, axis=0).eval() # 按列降维，求每一列的平均值，减少第零个维度

array([2., 3.], dtype=float32)

![axis](./image/axis.jpg)

In [49]:
tf.reduce_mean(x, axis=1).eval() # 按行降维，求每一行的平均值，减少第一个维度

array([1.5, 3.5], dtype=float32)

In [56]:
# keepdims: If true, retains reduced dimensions with length 1.
tf.reduce_mean(x,axis=1,keepdims=True).eval() 

array([[1.5],
       [3.5]], dtype=float32)

tf.reduce_sum(
    input_tensor,
    axis=None,
    keepdims=None,
    name=None,
    reduction_indices=None,
    keep_dims=None
)

In [62]:
x = [[1., 2.],
     [3., 4.]]

In [57]:
tf.reduce_sum(x).eval()

10.0

In [58]:
tf.reduce_sum(x, axis=0).eval()

array([4., 6.], dtype=float32)

In [61]:
tf.reduce_sum(x,axis=0,keepdims=True).eval()

array([[4., 6.]], dtype=float32)

In [59]:
tf.reduce_sum(x, axis=-1).eval()

array([3., 7.], dtype=float32)

In [60]:
tf.reduce_sum(x,axis=-1,keepdims=True).eval()

array([[3.],
       [7.]], dtype=float32)

In [63]:
tf.reduce_mean(tf.reduce_sum(x, axis=-1)).eval()

5.0

## Argmax with axis

tf.argmax(
    input,
    axis=None,
    name=None,
    dimension=None,
    output_type=tf.int64
)

Returns the index with the largest value across axes of a tensor.

In [64]:
x = [[0, 1, 2],
     [2, 1, 0]]
tf.argmax(x, axis=0).eval()

array([1, 0, 0], dtype=int64)

In [65]:
tf.argmax(x, axis=1).eval()

array([2, 0], dtype=int64)

In [66]:
tf.argmax(x, axis=-1).eval()

array([2, 0], dtype=int64)

## Reshape, squeeze, expand_dims

**tf.reshape**(
    tensor,
    shape,
    name=None
)

Given tensor, this operation returns a tensor that has the same values as tensor with shape shape

In [67]:
t = np.array([[[0, 1, 2], 
               [3, 4, 5]],
              
              [[6, 7, 8], 
               [9, 10, 11]]])
t.shape

(2, 2, 3)

In [68]:
tf.reshape(t, shape=[-1, 3]).eval()

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [69]:
tf.reshape(t, shape=[-1, 1, 3]).eval()

array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]]])

**tf.squeeze**(
    input,
    axis=None,
    name=None,
    squeeze_dims=None
)


Removes dimensions of size 1 from the shape of a tensor.  
For example:  
>'t' is a tensor of shape [3,1]  
>tf.shape(tf.squeeze(t)) # [3,]

In [73]:
tf.squeeze([[0], [1], [2]]).eval()

array([0, 1, 2])

In [72]:
tf.shape(tf.squeeze([[0],[1],[2]])).eval()

array([3])

Or, to remove specific size 1 dimensions:  
> 't' is a tensor of shape [1, 2, 1, 3, 1, 1]  
> tf.shape(tf.squeeze(t, [2, 4]))  # [1, 2, 3, 1]

In [85]:
t = tf.reshape(np.arange(6),shape=[1,2,1,3,1,1])
print('t:',t.eval())
print('shape:',tf.shape(t).eval())

t: [[[[[[0]]

    [[1]]

    [[2]]]]



  [[[[3]]

    [[4]]

    [[5]]]]]]
shape: [1 2 1 3 1 1]


In [84]:
tf.shape(tf.squeeze(t,[2,4])).eval()

array([1, 2, 3, 1])

**tf.expand_dims**(
    input,
    axis=None,
    name=None,
    dim=None
)

Inserts a dimension of 1 into a tensor's shape.

In [87]:
tf.expand_dims([0, 1, 2], 0).eval()  # shape[3,] ==>[1,3]

array([[0, 1, 2]])

In [89]:
tf.expand_dims([0, 1, 2], 1).eval() # shape [3,] ==> [3,1]

array([[0],
       [1],
       [2]])

## One hot

**tf.one_hot**(
    indices,
    depth,
    on_value=None,
    off_value=None,
    axis=None,
    dtype=None,
    name=None
)

In [92]:
indices = [0,1,2]
depth = 3
tf.one_hot(indices, depth).eval()

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)

In [93]:
tf.one_hot([[0], [1], [2], [0]], depth=3).eval()

array([[[1., 0., 0.]],

       [[0., 1., 0.]],

       [[0., 0., 1.]],

       [[1., 0., 0.]]], dtype=float32)

In [95]:
tf.shape(tf.one_hot([[0], [1], [2], [0]], depth=3)).eval()

array([4, 1, 3])

In [96]:
t = tf.one_hot([[0], [1], [2], [0]], depth=3)
tf.reshape(t, shape=[-1, 3]).eval()

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]], dtype=float32)

## casting

**tf.cast**(
    x,
    dtype,
    name=None
)  
Casts a tensor to a new type

In [97]:
tf.cast([1.8, 2.2, 3.3, 4.9], tf.int32).eval()

array([1, 2, 3, 4])

In [98]:
tf.cast([True, False, 1 == 1, 0 == 1], tf.int32).eval()

array([1, 0, 1, 0])

## Stack

**tf.stack**(
    values,
    axis=0,
    name='stack'
)

Stacks a list of rank-R tensors into one rank-(R+1) tensor.

In [99]:
x = [1, 4]
y = [2, 5]
z = [3, 6]
# Pack along first dim.
tf.stack([x, y, z]).eval()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [100]:
tf.stack([x, y, z], axis=1).eval()

array([[1, 2, 3],
       [4, 5, 6]])

## Ones like and Zeros like

In [101]:
x = [[0, 1, 2],
     [2, 1, 0]]

tf.ones_like(x).eval()

array([[1, 1, 1],
       [1, 1, 1]])

In [102]:
tf.zeros_like(x).eval()

array([[0, 0, 0],
       [0, 0, 0]])

## Zip


In [103]:
for x, y in zip([1, 2, 3], [4, 5, 6]):
    print(x, y)

1 4
2 5
3 6


In [104]:
for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x, y, z)

1 4 7
2 5 8
3 6 9


## Transpose

**tf.transpose**(
    a,
    perm=None,
    name='transpose',
    conjugate=False
)

Transposes a. Permutes the dimensions according to perm

In [105]:
t = np.array([[[0, 1, 2], [3, 4, 5]], [[6, 7, 8], [9, 10, 11]]])
pp.pprint(t.shape)
pp.pprint(t)

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])


![transpose](./image/transpose1.png)

In [106]:
t1 = tf.transpose(t, [1, 0, 2])
pp.pprint(sess.run(t1).shape)
pp.pprint(sess.run(t1))

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 6,  7,  8]],

       [[ 3,  4,  5],
        [ 9, 10, 11]]])


![transpose](./image/transpose2.png)

In [107]:
t = tf.transpose(t1, [1, 0, 2])
pp.pprint(sess.run(t).shape)
pp.pprint(sess.run(t))

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])


In [108]:
t2 = tf.transpose(t, [1, 2, 0])
pp.pprint(sess.run(t2).shape)
pp.pprint(sess.run(t2))

(2, 3, 2)
array([[[ 0,  6],
        [ 1,  7],
        [ 2,  8]],

       [[ 3,  9],
        [ 4, 10],
        [ 5, 11]]])


In [109]:
t = tf.transpose(t2, [2, 0, 1])
pp.pprint(sess.run(t).shape)
pp.pprint(sess.run(t))

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])
